### ISSUE TITLE
Cannot define method `nodeToParentTransform' because no Objective-C stub was pre-compiled

### ISSUE THREAD

**Issue by imranansari** [rubymotion-community/Joybox#2]
Any idea how to resolve this error?

```
 Simulate ./build/iPhoneSimulator-6.1-Development/Joybox.app
(main)> Cannot define method `nodeToParentTransform' because no Objective-C stub was pre-compiled for types `{CGAffineTransform=ffffff}@:'. Make sure you properly link with the framework or library that defines this message.
*** simulator session ended with error: Error Domain=DTiPhoneSimulatorErrorDomain Code=1 "The simulated application quit." UserInfo=0x10060ca40 {NSLocalizedDescription=The simulated application quit., DTiPhoneSimulatorUnderlyingErrorCodeKey=-1}
rake aborted!
Command failed with status (1): [DYLD_FRAMEWORK_PATH="/Applications/Xcode.a...]
/Library/RubyMotion/lib/motion/project.rb:102:in `block in <top (required)>'
/Users/iansari/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
/Users/iansari/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by NSCoder** [comment]
Yes is a problem to the bridgesupport file, the thing is that the method does not have the correct type in the definition. Can you give me more info about what are you trying to accomplish so i can fix it?

**Comment by NSCoder** [comment]
It was a bug difficult to track, but is fixed! Please update to the latest version.

**Comment by tmilewski** [comment]
I seem to be having the same issue (I'm using 0.0.5):

```
  Simulate ./build/iPhoneSimulator-6.1-Development/Gorillas.app
Cannot define method `nodeToParentTransform' because no Objective-C stub was pre-compiled for types `{CGAffineTransform=ffffff}@:'. Make sure you properly link with the framework or library that defines this message.
(main)> *** simulator session ended with error: Error Domain=DTiPhoneSimulatorErrorDomain Code=1 "The simulated application quit." UserInfo=0x1001242f0 {NSLocalizedDescription=The simulated application quit., DTiPhoneSimulatorUnderlyingErrorCodeKey=-1}
rake aborted!
Command failed with status (1): [DYLD_FRAMEWORK_PATH="/Applications/Xcode.a...]
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in `call'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in `sh'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/file_utils_ext.rb:37:in `sh'
/Library/RubyMotion/lib/motion/project.rb:102:in `block in <top (required)>'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/task.rb:205:in `block in invoke_prerequisites'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/task.rb:203:in `each'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/task.rb:183:in `block in invoke_with_call_chain'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385@global/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in `eval'
/Users/tmilewski/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => default => simulator
(See full trace by running task with --trace)
```

**Comment by NSCoder** [comment]
Can you help me running this on your machine, to see if this fixes it?

1.- Delete .repl_history file
2.- rake clean
3.- gem uninstall -a joybox
4.- gem install joybox
5.- rake

The problem is related to one corrupted .bridgesupport, so i think this should fix it.

If don't can you help me with some info? So i can fixed fast! :)

1.- Is the project new? or you are starting from a demo one?
2.- If the project is a demo, do you see the vendor folder in it?
3.- Have you install other version of the gem?

Also it will help me a lot if you can get me the gem folder, for inspection only.

Thanks for the report!

**Comment by tmilewski** [comment]
Thanks a lot for the quick response.

I did it twice. Once where I forgot to remove .repl_history (didn't work) and once where I did remove .repl_history (worked).

I'm good to go!

If anyone else has this issue, I'm more than happy to share additional information. Just let me know.

Thanks again!

**Comment by NSCoder** [comment]
\o/ Great! I am glad it work!
