### ISSUE TITLE
OSX: Closing game with the red button causes the game to exit poorly.

### ISSUE THREAD

**Issue by burtlo** [rubymotion-community/Joybox#25]
```
motion create --template=joybox-osx crash-test
cd crash-test
rake
```
- Left-click on the red X button on the title bar to close the game.

```
$ rake
     Build ./build/MacOSX-10.8-Development
     Build /Users/burtlo/.rvm/gems/ruby-1.9.3-p429@gaming/gems/joybox-1.0.0/vendor/vendor-osx/cocos_2d
     Build /Users/burtlo/.rvm/gems/ruby-1.9.3-p429@gaming/gems/joybox-1.0.0/vendor/vendor-osx/box_2d
       Run ./build/MacOSX-10.8-Development/memo-test.app/Contents/MacOS/memo-test
(main)> 2013-05-22 13:27:18.427 memo-test[51131:707] gl_view.rb:47:in `viewDidMoveToSuperview': undefined method `bounds' for nil:NilClass (NoMethodError)
2013-05-22 13:27:18.428 memo-test[51131:707] gl_view.rb:47:in `viewDidMoveToSuperview': undefined method `bounds' for nil:NilClass (NoMethodError)
2013-05-22 13:27:18.429 memo-test[51131:707] (
    0   CoreFoundation                      0x00007fff86c1fb06 __exceptionPreprocess + 198
    1   libobjc.A.dylib                     0x00007fff833b13f0 objc_exception_throw + 43
    2   memo-test                           0x00000001024c4253 _ZL10__vm_raisev + 371
    3   memo-test                           0x00000001024c4323 rb_vm_raise + 163
    4   memo-test                           0x00000001024031d9 rb_exc_raise + 9
    5   memo-test                           0x00000001024c5165 rb_vm_method_missing + 677
    6   memo-test                           0x00000001024b462c rb_vm_dispatch + 3228
    7   memo-test                           0x00000001024b5d7a rb_vm_trigger_method_missing + 746
    8   memo-test                           0x00000001024b501e rb_vm_dispatch + 5774
    9   memo-test                           0x00000001023064ac vm_dispatch + 540
    10  memo-test                           0x0000000102308342 rb_scope__viewDidMoveToSuperview__ + 226
    11  memo-test                           0x0000000102308469 __unnamed_22 + 9
    12  AppKit                              0x00007fff87aa1a5d -[NSView _setSuperview:] + 1956
    13  AppKit                              0x00007fff87aa42ce -[NSView removeFromSuperview] + 421
    14  AppKit                              0x00007fff87bd1a7f -[NSView removeFromSuperviewWithoutNeedingDisplay] + 39
    15  AppKit                              0x00007fff87ac255b -[NSView _finalizeWithReferenceCounting] + 965
    16  AppKit                              0x00007fff87ac216e -[NSView dealloc] + 42
    17  libobjc.A.dylib                     0x00007fff833aa230 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 464
    18  CoreFoundation                      0x00007fff86bbcd72 _CFAutoreleasePoolPop + 34
    19  Foundation                          0x00007fff87003ada -[NSAutoreleasePool drain] + 154
    20  AppKit                              0x00007fff87ac42ae -[NSApplication run] + 736
    21  AppKit                              0x00007fff87a68c06 NSApplicationMain + 869
    22  memo-test                           0x00000001022f2097 main + 231
    23  libdyld.dylib                       0x00007fff8b2fb7e1 start + 0
)
2013-05-22 13:27:18.430 memo-test[51131:707] *** -[NSAutoreleasePool drain]: This pool has already been drained, do not release it (double release).
```

**Comment by NSCoder** [comment]
Thank you Franklin for the report!

Now is fixed in the repo and it will be deployed in the next version :)
