### ISSUE TITLE
Joybox causing errors with latest RubyMotion

### ISSUE THREAD

**Issue by gpurkins** [rubymotion-community/Joybox#69]
I installed Joybox to do the default tutorial, and I started getting errors on rake.

Removing Joybox with the recommended method left my RubyMotion install giving these errors:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': cannot load such file -- /Users/george/Library/RubyMotion/command/joybox_generate_command.rb (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Library/RubyMotion/lib/motion/project/command.rb:82:in `block in <top (required)>'
    from /Library/RubyMotion/lib/motion/project/command.rb:82:in `each'
    from /Library/RubyMotion/lib/motion/project/command.rb:82:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Library/RubyMotion/lib/motion/command.rb:156:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Library/RubyMotion/lib/motion/../../bin/motion:12:in `<main>'
```

This error persists through reinstall. What the heck is Joybox doing?

**Comment by gpurkins** [comment]
Fixed it by going to ~/Library/RubyMotion/templates and removing joybox-*.rb.

Looks like RM got upset by having those there. Gem uninstaller should remove that stuff!

Phew!

**Comment by Dx** [comment]
Remove them also from ~/Library/RubyMotion/command

:)

**Comment by n-studio** [comment]
Fixed with RubyMotion 2.23!

**Comment by kakubei** [comment]
This is really, really bad. What a bad setup. And the gem uninstaller of course did not do it's job. This just bit me. Glad I found this entry.

**Comment by rebelwarrior** [comment]
bit me too.
Though I only needed to remove the files in ~/Library/RubyMotion/command to fix it.
